name: index_cut
description: "The widget represents a screen like an index cut"
version: 0.1.0
homepage: https://github.com/Shoryu-Y
repository: https://github.com/Shoryu-Y/index_cut
View/report issues: https://github.com/Shoryu-Y/index_cut/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
